const { test } = require('node:test')
const assert = require('node:assert/strict')
const { medusaToMinor, minorToMedusa } = require('../.test-build/domain/money')
const { evaluateDeliveryPolicy, parseDeliveryPolicy } = require('../.test-build/domain/delivery-policy')
const { expandCombo, parseComboSpec } = require('../.test-build/domain/combo')
const { sliceEnabled } = require('../.test-build/domain/slice-guard')
const policy = { rule_id:'qa_rule', version:1, currency_code:'brl', sales_channel_id:'qa_sc', region_id:'qa_reg', postal_code_from:'00000000', postal_code_to:'00000099', minimum_order_minor:1000, base_fee_minor:900, threshold_minor:3000, subsidy_cap_minor:900, enabled:true, promotion_active:true, starts_at:null, ends_at:null }
const cart = { currency_code:'brl', sales_channel_id:'qa_sc', region_id:'qa_reg', item_total:25, shipping_address:{country_code:'br',postal_code:'00000001'} }
const spec = { version:1, sales_channel_id:'qa_sc', slots:[{id:'main',min:1,max:1,options:[{variant_id:'burger',max_quantity:1}]},{id:'drink',min:1,max:1,options:[{variant_id:'water',max_quantity:1},{variant_id:'juice',max_quantity:1}]},{id:'extra',min:0,max:1,options:[{variant_id:'dessert',max_quantity:1}]}] }
const selections = [{slot_id:'main',variant_id:'burger',quantity:1},{slot_id:'drink',variant_id:'water',quantity:1}]
for (const [major, minor] of [[0,0],[17.97,1797],['79.90',7990],[0.1+0.2,30]]) test(`BRL conversion ${major}`,()=>assert.equal(medusaToMinor(major),minor))
test('minor to Medusa is not 100x inflated',()=>assert.equal(minorToMedusa(1797),17.97))
for (const x of [undefined,null,true,NaN,Infinity,-1,'','1e2','1,00',0.001]) test(`reject monetary value ${String(x)}`,()=>assert.throws(()=>medusaToMinor(x)))
test('invalid minor amount rejected',()=>assert.throws(()=>minorToMedusa(1.5)))
test('published policy computes five-real gap',()=>assert.equal(evaluateDeliveryPolicy(policy,cart).gapMinor,500))
test('threshold excludes shipping charges',()=>assert.equal(evaluateDeliveryPolicy(policy,{...cart,total:34,shipping_total:9}).finalFeeMinor,900))
test('threshold inclusive',()=>assert.equal(evaluateDeliveryPolicy(policy,{...cart,item_total:30}).finalFeeMinor,0))
test('one cent below does not qualify',()=>assert.equal(evaluateDeliveryPolicy(policy,{...cart,item_total:29.99}).gapMinor,1))
test('cap remains paid freight',()=>assert.equal(evaluateDeliveryPolicy({...policy,subsidy_cap_minor:400},{...cart,item_total:30}).finalFeeMinor,500))
test('future promotion charges normal freight',()=>assert.equal(evaluateDeliveryPolicy({...policy,starts_at:'2030-01-01T00:00:00Z'},cart,0).status,'unavailable'))
test('promotion end is exclusive',()=>assert.equal(evaluateDeliveryPolicy({...policy,ends_at:'2026-09-20T20:00:00Z'},{...cart,item_total:30},Date.parse('2026-09-20T20:00:00Z')).finalFeeMinor,900))
test('inactive incentive never advertises free freight',()=>assert.equal(evaluateDeliveryPolicy({...policy,promotion_active:false},{...cart,item_total:30}).finalFeeMinor,900))
for (const patch of [{currency_code:'usd'},{sales_channel_id:'other'},{region_id:'other'},{item_total:9.99},{shipping_address:null},{shipping_address:{country_code:'us',postal_code:'00000001'}},{shipping_address:{country_code:'br',postal_code:'00000100'}}]) test(`reject out of scope ${JSON.stringify(patch)}`,()=>assert.throws(()=>evaluateDeliveryPolicy(policy,{...cart,...patch})))
for (const patch of [{threshold_minor:0},{base_fee_minor:-1},{subsidy_cap_minor:1.1},{version:0},{postal_code_from:'00000999'},{starts_at:'2026-09-20'},{enabled:'false'}]) test(`reject invalid policy ${JSON.stringify(patch)}`,()=>assert.throws(()=>parseDeliveryPolicy({...policy,...patch})))
test('valid combo is deterministic and does not mutate selections',()=>{const copy=structuredClone(selections);assert.equal(expandCombo(spec,selections,'qa_sc').length,2);assert.deepEqual(selections,copy)})
test('optional modifier accepted',()=>assert.equal(expandCombo(spec,[...selections,{slot_id:'extra',variant_id:'dessert',quantity:1}],'qa_sc').length,3))
for (const choices of [[],selections.slice(0,1),[...selections,selections[0]],[{...selections[0],quantity:2},selections[1]],[{...selections[0],variant_id:'unknown'},selections[1]],[{...selections[0],unit_price:0},selections[1]],[{...selections[0],quantity:0},selections[1]]]) test(`invalid combo ${JSON.stringify(choices)}`,()=>assert.throws(()=>expandCombo(spec,choices,'qa_sc')))
test('cross-channel combo rejected',()=>assert.throws(()=>expandCombo(spec,selections,'another_sc')))
test('reversed slot bounds rejected',()=>assert.throws(()=>parseComboSpec({...spec,slots:[{...spec.slots[0],min:2,max:1}]})))
test('disabled by default',()=>assert.equal(sliceEnabled({APP_ENV:'test'}),false))
test('test slice allowed',()=>assert.equal(sliceEnabled({APP_ENV:'test',VINTAGE_SLICE_ENABLED:'true'}),true))
for (const APP_ENV of ['staging','production',undefined]) test(`cannot enable slice in ${APP_ENV}`,()=>assert.throws(()=>sliceEnabled({APP_ENV,VINTAGE_SLICE_ENABLED:'true'})))
